apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-metrics-reader-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k8s-metrics-reader
subjects:
  - kind: ServiceAccount
    name: k8s-metrics-reader
    namespace: k-metrics
